language: node_js
node_js:
 - "4.4.7"
notifications:
  email: false
before_deploy:
- test $TRAVIS_TEST_RESULT = 0
jobs:
  include:
    - stage: run tests
      script:
        # Ensure Travis aborts without running tests if the lockfile needs updating
        - set -e
        - ./check-lockfile.sh
        - yarn test
    - stage: heroku deploy
      script: echo "Deploying to Heroku ..."
      deploy:
        - provider: heroku    # Deploy master to Heroku - production (http://govuk-elements.herokuapp.com/)
          api_key:
            secure: nQCOBk2EnuJ0yaC0cO2RabfLlF+3WiZ4MrLLBPt3l+fNQO69KcJZu59Npbt45f/ip6Dv8cEGxdzSqzNsPu/XB+fmyAZd1bml0u7JMKWNQeVLKddoM+A1ETFSyXHoM/Ra3Qw8+2XS/ZJNTAD7BGibSh8SvzYdg9fy9kCN77Sn9Ro=
          app: govuk-elements
          on: master
        - provider: heroku    # Deploy master to Heroku - review (http://govuk-elements-review.herokuapp.com/)
          api_key:
            secure: nQCOBk2EnuJ0yaC0cO2RabfLlF+3WiZ4MrLLBPt3l+fNQO69KcJZu59Npbt45f/ip6Dv8cEGxdzSqzNsPu/XB+fmyAZd1bml0u7JMKWNQeVLKddoM+A1ETFSyXHoM/Ra3Qw8+2XS/ZJNTAD7BGibSh8SvzYdg9fy9kCN77Sn9Ro=
          app: govuk-elements-review
          on: master
    - stage: tag create, npm release, GitHub release
      script: echo "Running create-release.sh ..."
      deploy:
        - provider: script    # (If version.txt is updated) - create a new tag and push to Github, update the latest-release branch
          script: ./create-release.sh
          on: master
        - provider: heroku    # For tagged commits, update the release Heroku app (http://govuk-elements-sass-release.herokuapp.com/)
          api_key:
            secure: nQCOBk2EnuJ0yaC0cO2RabfLlF+3WiZ4MrLLBPt3l+fNQO69KcJZu59Npbt45f/ip6Dv8cEGxdzSqzNsPu/XB+fmyAZd1bml0u7JMKWNQeVLKddoM+A1ETFSyXHoM/Ra3Qw8+2XS/ZJNTAD7BGibSh8SvzYdg9fy9kCN77Sn9Ro=
          app: govuk-elements-sass-release
        - provider: script
          script: echo "Deploying to npm ..."
          script: cd packages/govuk-elements-sass/
        - provider: npm       # For tagged commits, update the NPM package (https://www.npmjs.com/package/govuk-elements-sass)
          email: govuk-dev@digital.cabinet-office.gov.uk
          api_key:
            secure: CW79rsUR5MFR+YyIsmwhbrndukNjzoKstp2SKupdEzUYTthnzsDxz2CGgI3SwwIcxPh41onxkDZm5R0ZvxwFQf4R+IJEhM94KqjwLdVE5bkKPD0JNYGbYRTDrTCYb74InvjN6LIhYvQwcKO+ThaiMA1IttEc4vCzKHPKKbPv340=
        - provider: script
          script: echo "Deploying to GitHub releases ..."
        - provider: releases  # For tagged commits, upload the contents of packages/govuk-elements-sass/ to GitHub releases
          api_key:
            secure: HZD7iqjcf/Yg792jMqksiVsCSQJSZG2TJ77EIGNh7qsdmCSJneUKPpeohQIEvkpjKiz+RyP4v0UqHx9lxHx7rBDmzOdTUCKAV3biTFvmf/W6IUb4UGXbjsDA5AMlNgpCdy4xT2iYBSyUKRR4qLjLDITduDoRQZFET5Z52nzcJgo=
          file_glob: true
          file: packages/govuk-elements-sass/*
          skip_cleanup: true
          on:
            tags: true
            all_branches: true
sudo: false
env:
  global:
    secure: eFtS+dlf00c3h4Rpp1FSZw6wOmZPmY4lYbqPV6MQa+VUgh+FRbUYOjDJP3UFaTsWNxMIL4mhEKFYLnkVftBdz1FgPjhIO3jNXleGMgVVedtD+qo5hTu1KI39t68K2YcELx9+kzeccX77WVmv/qJTVg7+f84WP9ebzVOJCQprJuw=
